# Changes directory to the downloaded git
os.chdir('/content/Saber_Box/Python Definitions/')

python_definition_list = ['Analyze_ScoreBox_Lights.py', 
                          'apply_mask.py', 
                          'average_list.py', 
                          'average_list_without_null.py', 
                          'bbox_output.py', 
                          'bell_guard_detection_test.py',
                          'Bell_Guard_Position_Finding.py',
                          'Bell_Guard_Position_Tracking.py',
                          'boundary_box_overlap.py',
                          'boundary_box_test.py',
                          'box_size_finder.py',
                          'camera_motion_adjustment.py',
                          'clip_vector_generator.py',
                          'clip_vector_np_save.py',
                          'color_tester.py',
                          'create_boundary_box.py',
                          'create_difference_array.py',
                          'create_folder_hierarchy.py',
                          'create_overlay_image.py',
                          'create_representative_image.py',
                          # 'create_title_card.py',
                          'create_title_card_compatible.py',
                          'create_tracking_masks.py',
                          'darknet_helper.py',
                          'determine_starting_frame.py',
                          'display_instances.py',
                          'downsample_fps.py',
                          'draw_Bell_Guard_Position.py',
                          'engarde_failure_test.py',
                          'engarde_position.py',
                          'evaluate_model.py',
                          'exclusion_area_simplification.py',
                          'exclusion_area_simplification_recursion.py',
                          'export_scorebox.py',
                          'Find_Array_Max_Value.py',
                          'Find_Difference_And_Format.py',
                          'Find_ScoreBox_Default.py',
                          'frame_comparison_ssim.py',
                          'hms_string.py',
                          'image_export.py',
                          'Left_Right_Test.py',
                          'light_color_comparison.py',
                          'list_threshold_test.py',
                          'load_clip.py',
                          'load_clip_vector.py',
                          'Load_ScoreBox_Image.py',
                          'make_video.py',
                          'mask_image.py',
                          'mean_of_a_numpy_percentile.py',
                          'Most_Recent_Sync_File.py',
                          'motion_difference_tracking.py',
                          'Move_Sync_File_for_Analysis.py',
                          'multiple_box_determination.py',
                          'number_of_files_in_dir.py',
                          'position_down_scale.py',
                          'position_linear_approximation.py',
                          'prepare_video_frames.py',
                          'process_video_clip.py',
                          'random_colors.py',
                          'read_video.py',
                          'reconcile_assumed_and_detected_lights.py',
                          'run_human_pose.py',
                          'saturation_test.py',
                          # 'save_ffmpeg.py',
                          # 'save_ffmpeg_compatible.py',
                          'scorebox_bbox.py',
                          'scoring_box_lights.py',
                          'setup_clip_directories.py',
                          'simple_clip_vector_generator.py',
                          'smooth_clip_vector.py',
                          'symmetry_test.py',
                          'test_and_remove_duplicate_frames.py',
                          'torso_detection_test.py',
                          'torso_failure_test.py',
                          'torso_position_failure_test.py',
                          'tracking_box_default.py',
                          'update_scorebox_csv.py',
                          'weight_average_list.py',
                          'weighted_average_array.py',
                          'yolov4_run_image.py',
                          # 'youtube_clip_compatible.py'
                          # 'youtube_clip.py'
                          ]

for file in python_definition_list:
  execfile(file)
